### ISSUE TITLE
Divide by zero

### ISSUE THREAD

**Issue by adammaskulka** [mmobin789/pixel#2] opened 2020-06-23 11:04 UTC
I'm getting java.lang.ArithmeticException: divide by zero when I set image size to WRAP_CONTENT

`Process: com.example.ecample, PID: 17044
    java.lang.ArithmeticException: divide by zero
        at io.pixel.android.utils.BitmapUtils.calculateInSampleSize(BitmapUtils.kt:90)
        at io.pixel.android.utils.BitmapUtils.access$calculateInSampleSize(BitmapUtils.kt:10)
        at io.pixel.android.utils.BitmapUtils$getDecodedBitmapFromByteArray$1.onHeaderDecoded(BitmapUtils.kt:24)
        at android.graphics.ImageDecoder.callHeaderDecoded(ImageDecoder.java:1720)
        at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1860)
        at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1851)
        at io.pixel.android.utils.BitmapUtils.getDecodedBitmapFromByteArray(BitmapUtils.kt:20)
        at io.pixel.android.utils.DownloadUtils.getBitmapFromURL(DownloadUtils.kt:18)
        at io.pixel.pixel.loader.load.LoadAdapter.downloadImage(LoadAdapter.kt:52)
        at io.pixel.android.loader.download.ImageDownload$onReady$1.invokeSuspend(ImageDownload.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)`

**Comment by mmobin789** [comment] 2020-06-23 12:06
@adammaskulka Pixel loads an image strictly based on the size of image view as specified in the article. In your XML, change size of your image view to density pixels - dp set this equal to size (w x h) of your image you will be displaying in it or provide a size (w x h) of image via pixel options class when loading it. And I suggest you read the article again in detail as it covers above mentioned use-cases.

The problem is occured because pixel doesn't know the size of image view or image for downsampling. It has to know the size of image in advance to load a downsampled version.

This should fix your issue let me know so I can close this.

Thanks.

 [https://medium.com/better-programming/introducing-pixel-a-new-kotlin-image-loading-library-for-android-a37a7a192f73](url)

**Comment by mmobin789** [comment] 2020-10-07 18:59
@adammaskulka This is fixed in new release.

This was due to library being bound to image view dimensions.

Now its fixed.

Thanks for reporting it.

**Closed** 2020-10-07 19:01 UTC
Labels: enhancement, help wanted
